name: BookEnvironment
channels:
  - defaults
  - conda-forge
  - anaconda-fusion
  - anaconda-platform
dependencies:
  - markdown
  - pip
  #- mypy # is an optional static type checker for Python.
  #- numpy # The fundamental package for scientific computing with Python.
  #- psutil # Is a cross-platform library for retrieving information onrunning processes and system utilization (CPU, memory, disks, network) in Python.
  - toolz # Toolz provides a set of utility functions for iterators, functions, and dictionaries. These functions interoperate well and form the building blocks of common data analytic operations.
  #- matplotlib # Is a comprehensive library for creating static, animated, and interactive visualizations in Python.
  #- dill # Can be used to store python objects to a file, but the primary usage is to send python objects across the network as a byte stream.
  #- pandas # Open source data analysis and manipulation tool, built on top of the Python programming language.
  - partd # Key-value byte store with appendable values. Partd stores key-value pairs. Values are raw bytes. We append on old values. Partd excels at shuffling operations.
  #- bokeh # Is an interactive visualization library for modern web browsers. It provides elegant, concise construction of versatile graphics, and affords high-performance interactivity over large or streaming datasets.
  - dask # Uses existing Python APIs and data structures to make it easy to switch between Numpy, Pandas, Scikit-learn to their Dask-powered equivalents.
  #- scipy # Is a Python-based ecosystem of open-source software for mathematics, science, and engineering.
  #- graphviz # Is open source graph visualization software.
  - notedown # Is a simple tool to create IPython notebooks from markdown (and r-markdown). notedown separates your markdown into code and not code.
  - pip:
      - enforce
      #- graphviz
      #- networkx
      #- pydot
      #- yapf
      #- astor
      #- showast # IPython notebook plugin for visualizing abstract syntax trees.
      - jupyter_contrib_nbextensions