#!/bin/bash

# Install and enable Jupyter nbextensions
# https://github.com/binder-examples/jupyter-extension
# https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html
echo postBuild: Installing Jupyter extensions...
jupyter contrib nbextension install --user
jupyter nbextension enable toc2/main --user
#jupyter nbextension enable exercise2/main --user

# Trust notebooks such that users can see their HTML and JS output
echo postBuild: Trusting notebooks ...
jupyter trust chapters/*.ipynb